version: "3"
services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: starter
      POSTGRES_USER: rust
      POSTGRES_PASSWORD: rustStarter
    ports:
      - 5433:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://rust:rustStarter@postgres/starter
      SESSION_KEY: badkeyabcdefghijklmnopqrstuvwxyzabcdef
    links:
      - postgres
    ports:
      - 8088:8088
    volumes:
      # Mount the src/ directory so we don't have to rebuild the Docker image
      # when we want to change some code
      - ./src:/app/src:ro
      - index:/app/tmp
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/app/target
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    entrypoint: npm run start -- --proxy http://127.0.0.1:8088
    links:
      - backend
    ports:
      - 3000:3000
    volumes:
      # Mount the app/ directory so live reload works
      - ./app:/app/app:ro

volumes:
  postgres-data:
  cargo-cache:
  target-cache:
  index: